# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8084bd543f7e554315e50afeb959190b815bc7e821bf918bf40b64d34dae6c48a7f54e2a21c8dfc586e6d96a915b53e7ff79948392234a224fa5a2ff1f74d802

test:
  secret_key_base: 2a70baad7d209df35e0fdd78d2c0b137108c4712bb0e375ed3190b12623188bb8fc1bc730edaf8a0ddc0a81804a31753e1a73fb1b10b315e71f5706a599819e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
